# Generated by Django 3.2.25 on 2024-06-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240626_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_time',
            field=models.TimeField(null=True),
        ),
    ]
